### ISSUE TITLE
Banner patterns crash client

### ISSUE THREAD

**Issue by RFKreborn** [Magistu/Knightly-Armory#10]
[crash-2022-07-23_15.55.48-client.txt](https://github.com/Magistu/Knightly-Armory/files/9174989/crash-2022-07-23_15.55.48-client.txt)

I'm on 1.18.2 with mod version 5.11. This crash only occurs when the waystones mod is installed. In order to cause the crash, you have to put an epic knight's banner pattern into the loom, and it will immediately crash the client.

**Comment by Lesley-Black-Velvet** [comment]
Good evening!

Apparently, I too have the same issue!

`Time: 8/3/22, 6:53 PM
Description: Rendering screen

java.lang.NullPointerException: Cannot invoke "net.minecraft.client.resources.model.Material.m_119194_(net.minecraft.client.renderer.MultiBufferSource, java.util.function.Function)" because "$$13" is null
	at net.minecraft.client.renderer.blockentity.BannerRenderer.m_112074_(BannerRenderer.java:136) ~[client-1.18.2-20220404.173914-srg.jar%23179!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.client.renderer.blockentity.BannerRenderer.m_112065_(BannerRenderer.java:125) ~[client-1.18.2-20220404.173914-srg.jar%23179!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.client.gui.screens.inventory.LoomScreen.m_7286_(LoomScreen.java:116) ~[client-1.18.2-20220404.173914-srg.jar%23179!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:supplementaries.mixins.json:LoomScreenFlagMixin,pl:mixin:APP:quark.mixins.json:client.LoomScreenMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screens.inventory.AbstractContainerScreen.m_6305_(AbstractContainerScreen.java:92) ~[client-1.18.2-20220404.173914-srg.jar%23179!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:AbstractContainerScreenAccessor,pl:mixin:APP:botania_xplat.mixins.json:client.AccessorAbstractContainerScreen,pl:mixin:APP:quark.mixins.json:client.ContainerScreenMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screens.inventory.LoomScreen.m_6305_(LoomScreen.java:76) ~[client-1.18.2-20220404.173914-srg.jar%23179!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:supplementaries.mixins.json:LoomScreenFlagMixin,pl:mixin:APP:quark.mixins.json:client.LoomScreenMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraftforge.client.ForgeHooksClient.drawScreenInternal(ForgeHooksClient.java:403) ~[forge-1.18.2-40.1.68-universal.jar%23184!/:?] {re:classloading}
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:396) ~[forge-1.18.2-40.1.68-universal.jar%23184!/:?] {re:classloading}
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:890) ~[client-1.18.2-20220404.173914-srg.jar%23179!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:create.mixins.json:GameRendererMixin,pl:mixin:APP:create.mixins.json:accessor.GameRendererAccessor,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1045) ~[client-1.18.2-20220404.173914-srg.jar%23179!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:APP:botania_xplat.mixins.json:client.AccessorMinecraft,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:blueprint.mixins.json:client.MinecraftMixin,pl:mixin:APP:ars_nouveau.mixins.json:light.ClientMixin,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:APP:ars_nouveau.mixins.json:camera.MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:664) ~[client-1.18.2-20220404.173914-srg.jar%23179!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:APP:botania_xplat.mixins.json:client.AccessorMinecraft,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:blueprint.mixins.json:client.MinecraftMixin,pl:mixin:APP:ars_nouveau.mixins.json:light.ClientMixin,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:APP:ars_nouveau.mixins.json:camera.MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:205) ~[client-1.18.2-20220404.173914-srg.jar%23179!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:31) ~[fmlloader-1.18.2-40.1.68.jar%2317!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149) [bootstraplauncher-1.0.0.jar:?] {}
`

**Comment by drakray** [comment]
Might be somewhat related, I got this https://pastebin.com/Ry6bvjC2 when updating GreekFantasy, which have
```
Fix a crash related to banner patterns (#95 and #98).
```
in it's changelog

Main error line is
```
Caused by: net.minecraft.ResourceLocationException: Non [a-z0-9/._-] character in path of location: magistuarmory:entity/heatershield/greekfantasy:spider
```
